### ISSUE TITLE
请问是下载`yay -S fcitx5-pinyin-moegirl`就能用吗？

### ISSUE THREAD

**Issue by 1900011604** [outloudvi/mw2fcitx#1]
我只运行了这个，没有运行`make`以及`sudo make install`。这样是否已经启用了萌娘百科词库？

**Comment by 1900011604** [comment]
![Screenshot_20201116_095310](https://user-images.githubusercontent.com/65082432/99204744-8c564e00-27f1-11eb-9324-27508479aaa5.png)
这里面已经有了，应该是能用的吧。

**Comment by outloudvi** [comment]
嗯。`fcitx5-pinyin-moegirl` 应该是包含了已经生成完毕的词库，不需要 `make` 和 `make install`。
