### ISSUE TITLE
考虑添加姓氏吗

### ISSUE THREAD

**Issue by xieyl07** [outloudvi/mw2fcitx#12]
https://zh.moegirl.org.cn/zh-cn/Category:%E6%8C%89%E5%A7%93%E6%B0%8F%E5%88%86%E7%B1%BB

**Comment by outloudvi** [comment]
暂时没有计划。主要考虑的原因是大多数用户可能并不会用到其中大多数词语；又因为姓氏集条目很多而长度短，容易和一般中文词语产生冲突，考虑到多音字自动转换问题，实际发生的冲突可能更多。

**Comment by xieyl07** [comment]
突然意识到我只是想顺利的打出角色(~老婆~)的名字, 比如和纱. 做到这件事, 想想就麻烦, 所以当我没说:)

**Comment by outloudvi** [comment]
如果是个别用户常用词的话，可以选择带有记忆用户词库功能的输入法。例如 RIME 的各平台应该都有类似功能。

**Comment by suiginko** [comment]
我在修改版的词库里添加了姓氏（单字姓除外）和基于姓氏分离出的名字
https://github.com/suiginko/moetype
