### ISSUE TITLE
好像有的名字在转换成词典的过程中丢失了

### ISSUE THREAD

**Issue by freeorca** [outloudvi/mw2fcitx#16]
用的是20240709 Release版本

有的名字在“titles.txt”里是有的，但在“moegirl.dict.yaml”里就没有了，比如“琴吹䌷”。看了下发现名字里带“䌷”字的基本全军覆没了，只有一个“柊䌷希”幸存。

**Comment by outloudvi** [comment]
感谢回报 bug！

「䌷」字是 [Unicode 0x4337](https://unicode.scarfboy.com/?s=%E4%8C%B7)，位于 CJK Unified Ideographs Extension A 区段，被目前代码里认为不是汉字，因此所有包含此字的词条都被跳过了：

<https://github.com/outloudvi/mw2fcitx/blob/083259df8691905dd6cbe2f5364c940faffaf7e1/mw2fcitx/exporters/opencc.py#L20>

测试例：

```python
import re

HANZI_RE = re.compile('^[\u4e00-\u9fa5]+$')
HANZI_RE.match("琴吹䌷") is not None # False
HANZI_RE.match("柊柚夕") is not None # True
```

目前的汉字判定方法会跳过一些 Extension A 区的汉字，这在 moegirl 词库的情况下确实引起了一些问题。后续会修正这里的判断逻辑，将这些问题正常识别并导出到词库。

（紬桑对不起，请不要打我）

[![Tsumugi is strong](https://github.com/user-attachments/assets/139058cc-30b8-4956-bffa-f2de9b591ab2)](https://www.facebook.com/AndyAshes0209/posts/220790101958365)

**Comment by outloudvi** [comment]
此问题已经在 #19 修复。下一版本的 moegirl 词典将包含这些新词语。感谢报告！
