### ISSUE TITLE
Release python package src

### ISSUE THREAD

**Issue by blackteahamburger** [outloudvi/mw2fcitx#22]
The PyPI package misses test files needed by test in Gentoo ebuild that I'm writing. So I need python package src release containing these files, thanks!

**Comment by outloudvi** [comment]
Good idea! Seems that [the official packaging guide](https://packaging.python.org/en/latest/discussions/package-formats/) is also recommending adding tests to sdists.

> In particular, wheels should never include tests and documentation, while sdists commonly do.

**Comment by outloudvi** [comment]
Please have a check at [mw2fcitx@0.15.0](https://pypi.org/project/mw2fcitx/0.15.0/) to see whether it can be of use for you.

**Comment by blackteahamburger** [comment]
Thanks!
