### ISSUE TITLE
关于证书验证失败的问题CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by shitlime** [outloudvi/mw2fcitx#5]
使用0.9.1版本时遇到了证书验证失败的问题：

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)>

上网搜索相关问题，经过一番修改和调试，将mw2fcitx\fetch.py的代码修改了：
```Python
import json
import certifi
from urllib.request import Request, urlopen
from urllib.parse import quote_plus
from mw2fcitx.utils import console
from mw2fcitx.retry import retry


class StatusError(Exception):

    def __init__(self, code):
        super().__init__("HTTP status is {}".format(code))


@retry()
def open_request(url):
    return urlopen(
        Request(
            url,
            headers={
                "User-Agent":
                    "MW2Fcitx/1.0; github.com/outloudvi/fcitx5-pinyin-moegirl"
            }), cafile=certifi.where())
```
……后面略
主要增加了`import certifi`以及`cafile=certifi.where()`解决证书验证的问题
由于我用的是旧版，不知道现在的版本有没有问题，就不提交pr了

**Comment by outloudvi** [comment]
感谢你的报告！

首先，建议使用最新的版本，因为旧版确实有一些 bug。

另外，[`certifi`](https://pypi.org/project/certifi/) 看起来是提供了使用系统 CA 之外的另一种解决方案。不过，通常我们认为系统 CA 是更新及时并且可以使用的，所以不会特意换用 `certifi`。

至于这里的 "certificate has expired" 的问题，既然换用 `certifi` 之后正常了，大概不是服务器证书真的过期，而是系统的 CA 证书库未有更新，所以建议对证书库（例如可能是一个叫 `ca-certificates` 的包）进行更新。考虑到这个时间点与证书库证书过期相关的事件，可能你的设备 CA 证书库受到了 Let's Encrypt 之前所用的 DST Root CA X3 过期问题的影响：

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
