### ISSUE TITLE
The latest release doesn't work

### ISSUE THREAD

**Issue by outloudvi** [outloudvi/mw2fcitx#8]
Seems to be a trick of `ghr` [we are using](https://github.com/outloudvi/mw2fcitx/blob/ca4fe1baf242bd188a320586083bb8523ccfe5c7/.github/workflows/build_dict.yml#L32) - the "latest" release on GitHub is still of the date Feb 18, which confuses the buildbot of archlinuxcn. As a result, archlinuxcn's package is not up to date.

(No wonder why I cannot type out names of MusicRay'n artists - many of those are created on March)

**Comment by imlonghao** [comment]
It seems there is no error log? and the build looks success.
https://github.com/outloudvi/mw2fcitx/runs/6888542675

**Comment by lisansas** [comment]
昨天的没了，看build为Error: Process completed with exit code 1.

**Comment by outloudvi** [comment]
> 昨天的没了，看build为Error: Process completed with exit code 1.

Thanks for reporting! However, they are different issues. Moved to #9.

**Comment by outloudvi** [comment]
Closing thanks for archlinuxcn/repo@4e63947ab00de8f1b977dc7933f0934c4feefaa4.
